INSERT INTO Movies (title, year, description, rating) VALUES
('The Shawshank Redemption', 1994, 'A man is wrongly imprisoned and finds hope.', 9.3),
('The Godfather', 1972, 'The aging patriarch transfers control of his empire.', 9.2),
('The Dark Knight', 2008, 'Batman faces the Joker in Gotham.', 9.0),
('Pulp Fiction', 1994, 'Stories of crime intertwine in Los Angeles.', 8.9),
('Forrest Gump', 1994, 'A simple man witnesses major historical events.', 8.8),
('Inception', 2010, 'A thief enters dreams to plant an idea.', 8.8),
('The Matrix', 1999, 'A hacker discovers reality is an illusion.', 8.7),
('Fight Club', 1999, 'An office worker forms an underground fight club.', 8.8),
('The Lord of the Rings: The Fellowship of the Ring', 2001, 'A hobbit begins a journey to destroy a ring.', 8.8),
('The Lord of the Rings: The Two Towers', 2002, 'The fellowship splits as war begins.', 8.7),
('The Lord of the Rings: The Return of the King', 2003, 'The final battle for Middle-earth.', 8.9),
('Interstellar', 2014, 'A team travels through a wormhole to save Earth.', 8.6),
('Gladiator', 2000, 'A general becomes a gladiator to seek revenge.', 8.5),
('The Prestige', 2006, 'Two magicians engage in a deadly rivalry.', 8.5),
('Whiplash', 2014, 'A drummer faces extreme training.', 8.5),
('The Departed', 2006, 'An undercover cop infiltrates a mob.', 8.5),
('The Lion King', 1994, 'A lion cub must reclaim his kingdom.', 8.5),
('Titanic', 1997, 'A romance blossoms on a doomed ship.', 7.8),
('Goodfellas', 1990, 'The rise and fall of a mob associate.', 8.7),
('Braveheart', 1995, 'A Scotsman leads a rebellion against England.', 8.3),
('Toy Story', 1995, 'Toys come to life when humans aren’t around.', 8.3),
('The Silence of the Lambs', 1991, 'A young FBI agent seeks help from a killer.', 8.6),
('Saving Private Ryan', 1998, 'Soldiers rescue a paratrooper in WWII.', 8.6),
('The Green Mile', 1999, 'A guard discovers a prisoner with a miracle.', 8.6),
('Schindler''s List', 1993, 'A man saves Jews during the Holocaust.', 9.0),
('Joker', 2019, 'A man descends into madness in Gotham.', 8.4),
('Avengers: Endgame', 2019, 'Heroes unite to undo the Snap.', 8.4),
('The Avengers', 2012, 'Earth’s mightiest heroes team up.', 8.0),
('Iron Man', 2008, 'A billionaire builds a high-tech suit.', 7.9),
('Spider-Man: No Way Home', 2021, 'Spider-Men unite across universes.', 8.3),
('Black Panther', 2018, 'A king defends his nation of Wakanda.', 7.3),
('The Incredibles', 2004, 'A superhero family hides in plain sight.', 8.0),
('Coco', 2017, 'A boy visits the Land of the Dead.', 8.4),
('Ratatouille', 2007, 'A rat becomes a chef in Paris.', 8.1),
('Up', 2009, 'A man flies his house to South America.', 8.2),
('WALL-E', 2008, 'A robot cleans a deserted Earth.', 8.4),
('Finding Nemo', 2003, 'A fish crosses the ocean to find his son.', 8.1),
('Inside Out', 2015, 'Personified emotions guide a young girl.', 8.1),
('Soul', 2020, 'A man discovers his true purpose.', 8.0),
('Luca', 2021, 'Sea monsters explore the human world.', 7.4),
('Turning Red', 2022, 'A girl turns into a red panda.', 7.0),
('Encanto', 2021, 'A girl in a magical family seeks her gift.', 7.3),
('Frozen', 2013, 'A princess unleashes icy powers.', 7.4),
('Frozen II', 2019, 'Elsa seeks the origin of her powers.', 6.8),
('Moana', 2016, 'A girl sails to save her island.', 7.6),
('Zootopia', 2016, 'A bunny cop solves a big case.', 8.0),
('Big Hero 6', 2014, 'A boy forms a superhero team.', 7.8),
('Tangled', 2010, 'A girl with long hair escapes her tower.', 7.7),
('Raya and the Last Dragon', 2021, 'A warrior seeks the last dragon.', 7.3),
-- (50 más continuando...)
('The Hunger Games', 2012, 'Teens fight in a televised battle.', 7.2),
('Catching Fire', 2013, 'A rebellion starts after the games.', 7.5),
('Mockingjay Part 1', 2014, 'The revolution intensifies.', 6.6),
('Mockingjay Part 2', 2015, 'The Capitol falls.', 6.5),
('Dune', 2021, 'A boy faces destiny on a desert planet.', 8.0),
('Dune: Part Two', 2024, 'War erupts on Arrakis.', 8.9),
('Avatar', 2009, 'Humans colonize a distant moon.', 7.8),
('Avatar: The Way of Water', 2022, 'The Sullys explore oceanic Pandora.', 7.6),
('Star Wars: A New Hope', 1977, 'A farm boy becomes a hero.', 8.6),
('The Empire Strikes Back', 1980, 'The Rebellion faces defeat.', 8.7),
('Return of the Jedi', 1983, 'Luke confronts his father.', 8.3),
('The Force Awakens', 2015, 'A new hero rises.', 7.8),
('The Last Jedi', 2017, 'The Resistance is cornered.', 6.9),
('The Rise of Skywalker', 2019, 'The saga concludes.', 6.5),
('Rogue One', 2016, 'Rebels steal Death Star plans.', 7.8),
('Solo', 2018, 'The origin of Han Solo.', 6.9),
('The Batman', 2022, 'Batman investigates a cryptic killer.', 7.9),
('Man of Steel', 2013, 'Superman chooses his destiny.', 7.1),
('Justice League', 2017, 'Heroes unite to stop Steppenwolf.', 6.1),
('Zack Snyder''s Justice League', 2021, 'The full vision of the League.', 8.0),
('Aquaman', 2018, 'A man claims the undersea throne.', 6.9),
('Wonder Woman', 2017, 'A warrior discovers mankind.', 7.4),
('Wonder Woman 1984', 2020, 'Diana faces a new threat.', 5.4),
('Shazam!', 2019, 'A boy gains adult superpowers.', 7.0),
('Black Adam', 2022, 'An antihero awakens in modern times.', 6.3),
('Deadpool', 2016, 'A mercenary becomes immortal.', 8.0),
('Deadpool 2', 2018, 'Wade protects a mutant boy.', 7.7),
('Logan', 2017, 'Wolverine’s final journey.', 8.1),
('X-Men: Days of Future Past', 2014, 'Past and future collide.', 7.9),
('X-Men: First Class', 2011, 'The origin of the X-Men.', 7.7),
('The Wolverine', 2013, 'Logan travels to Japan.', 6.7),
('X-Men Origins: Wolverine', 2009, 'Logan’s early life.', 6.6),
('The Social Network', 2010, 'The rise of Facebook.', 7.7),
('The Imitation Game', 2014, 'Alan Turing cracks Enigma.', 8.0),
('The Theory of Everything', 2014, 'Stephen Hawking’s journey.', 7.7),
('Bohemian Rhapsody', 2018, 'Freddie Mercury and Queen.', 7.9),
('Rocketman', 2019, 'The life of Elton John.', 7.3),
('La La Land', 2016, 'A jazz pianist and actress fall in love.', 8.0),
('The Greatest Showman', 2017, 'The rise of P.T. Barnum.', 7.6),
('Les Misérables', 2012, 'A man is pursued in post-revolution France.', 7.6),
('The Grand Budapest Hotel', 2014, 'A hotel concierge gets in trouble.', 8.1),
('Knives Out', 2019, 'A detective solves a family murder.', 7.9),
('Glass Onion', 2022, 'Another Benoit Blanc mystery.', 7.2),
('Everything Everywhere All at Once', 2022, 'A woman jumps through multiverses.', 8.7),
('Parasite', 2019, 'A poor family cons its way into wealth.', 8.6),
('Minari', 2020, 'A Korean family starts fresh in the US.', 7.5),
('Nomadland', 2020, 'A woman lives in her van.', 7.4),
('1917', 2019, 'Two soldiers race to stop a battle.', 8.3),
('The Irishman', 2019, 'A man reflects on his mob past.', 7.8),
('Once Upon a Time in Hollywood', 2019, 'Actors in 1969 LA.', 7.6),
('Oppenheimer', 2023, 'The father of the atomic bomb.', 8.8),
('Barbie', 2023, 'Barbie questions her reality.', 7.1),
('Tenet', 2020, 'A spy manipulates time to prevent war.', 7.3),
('No Time to Die', 2021, 'Bond faces his past.', 7.3),
('Skyfall', 2012, 'Bond protects M.', 7.8),
('Spectre', 2015, 'Bond uncovers a secret group.', 6.8);