INSERT INTO actors (firstname, lastname, bio, rating) VALUES
('Leonardo', 'DiCaprio', 'Actor estadounidense conocido por Titanic e Inception.', 9.2),
('Morgan', 'Freeman', 'Narrador y actor ganador del Oscar.', 9.0),
('Robert', 'De Niro', 'Icono del cine mafioso y colaborador de Scorsese.', 9.1),
('Al', 'Pacino', 'Reconocido por El Padrino y Scarface.', 9.0),
('Tom', 'Hanks', 'Actor versátil ganador de múltiples premios.', 8.9),
('Brad', 'Pitt', 'Actor y productor de películas exitosas.', 8.7),
('Johnny', 'Depp', 'Conocido por personajes excéntricos como Jack Sparrow.', 8.5),
('Christian', 'Bale', 'Conocido por su transformación física en papeles exigentes.', 8.8),
('Denzel', 'Washington', 'Actor poderoso con gran presencia escénica.', 9.0),
('Anthony', 'Hopkins', 'Legendario actor británico conocido por Hannibal.', 9.1),
('Matt', 'Damon', 'Actor y guionista reconocido por The Martian.', 8.6),
('Ben', 'Affleck', 'Actor y director ganador de un Oscar.', 8.2),
('Chris', 'Hemsworth', 'Famoso por su papel como Thor.', 8.0),
('Chris', 'Evans', 'Conocido por interpretar al Capitán América.', 8.3),
('Chris', 'Pratt', 'Protagonista de Guardianes de la Galaxia.', 8.1),
('Ryan', 'Reynolds', 'Actor canadiense conocido por Deadpool.', 8.2),
('Ryan', 'Gosling', 'Conocido por La La Land y Drive.', 8.4),
('Will', 'Smith', 'Actor y rapero, ganador de un Oscar.', 8.5),
('Hugh', 'Jackman', 'Actor australiano famoso por Wolverine.', 8.7),
('Keanu', 'Reeves', 'Actor querido por fans de Matrix y John Wick.', 8.6),
('Joaquin', 'Phoenix', 'Ganador del Oscar por Joker.', 9.0),
('Daniel', 'Day-Lewis', 'Considerado uno de los mejores actores vivos.', 9.5),
('Samuel', 'Jackson', 'Uno de los actores más prolíficos del cine.', 8.8),
('Edward', 'Norton', 'Actor intenso con papeles dramáticos fuertes.', 8.6),
('Jake', 'Gyllenhaal', 'Actor versátil en drama y suspenso.', 8.5),
('Tom', 'Cruise', 'Estrella de acción y productor.', 8.4),
('Michael', 'B. Jordan', 'Conocido por Black Panther y Creed.', 8.3),
('Mark', 'Ruffalo', 'Hulk del MCU y actor dramático.', 8.4),
('Robert', 'Downey Jr.', 'Famoso por Iron Man y Sherlock Holmes.', 9.0),
('Andrew', 'Garfield', 'Spider-Man y actor nominado al Oscar.', 8.4),
('Tobey', 'Maguire', 'Spider-Man original y actor reconocido.', 8.2),
('Paul', 'Rudd', 'Comediante y actor del MCU.', 8.0),
('Timothée', 'Chalamet', 'Actor joven con gran proyección.', 8.6),
('Zendaya', 'Coleman', 'Actriz, cantante y modelo.', 8.5),
('Emma', 'Stone', 'Ganadora del Oscar por La La Land.', 8.7),
('Emma', 'Watson', 'Conocida por Hermione en Harry Potter.', 8.3),
('Daniel', 'Radcliffe', 'Protagonista de la saga Harry Potter.', 8.1),
('Rupert', 'Grint', 'Reconocido por su papel de Ron Weasley.', 7.9),
('Jennifer', 'Lawrence', 'Ganadora del Oscar por Silver Linings Playbook.', 8.8),
('Natalie', 'Portman', 'Actriz y académica.', 8.7),
('Scarlett', 'Johansson', 'Actriz destacada en acción y drama.', 8.8),
('Florence', 'Pugh', 'Nueva estrella de Hollywood.', 8.4),
('Ana', 'de Armas', 'Actriz cubano-española en ascenso.', 8.3),
('Brie', 'Larson', 'Ganadora del Oscar y actriz de Marvel.', 8.2),
('Jessica', 'Chastain', 'Actriz poderosa en drama.', 8.7),
('Margot', 'Robbie', 'Actriz australiana famosa por Barbie y Wolf of Wall Street.', 8.6),
('Charlize', 'Theron', 'Ganadora del Oscar y actriz de acción.', 8.7),
('Gal', 'Gadot', 'Conocida por Wonder Woman.', 8.1),
('Angelina', 'Jolie', 'Actriz y humanitaria.', 8.2),
('Meryl', 'Streep', 'Actriz más nominada al Oscar en la historia.', 9.6),
('Kate', 'Winslet', 'Ganadora del Oscar por The Reader.', 8.9),
('Sandra', 'Bullock', 'Reconocida por comedia y drama.', 8.5),
('Julia', 'Roberts', 'Estrella del cine de los 90.', 8.4),
('Nicole', 'Kidman', 'Actriz australiana de gran rango.', 8.6),
('Amy', 'Adams', 'Frecuente nominada al Oscar.', 8.7),
('Rachel', 'McAdams', 'Actriz de comedia y romance.', 8.3),
('Emily', 'Blunt', 'Reconocida por roles de acción y drama.', 8.5),
('Anne', 'Hathaway', 'Ganadora del Oscar y estrella de cine.', 8.5),
('Helena', 'Bonham Carter', 'Estilo gótico y papeles excéntricos.', 8.4),
('Kristen', 'Stewart', 'De Crepúsculo a cine independiente.', 8.2),
('Robert', 'Pattinson', 'De vampiro a Batman.', 8.3),
('Jared', 'Leto', 'Actor y cantante ganador del Oscar.', 8.1),
('Woody', 'Harrelson', 'Actor versátil con toques cómicos.', 8.4),
('Bryan', 'Cranston', 'Conocido por Breaking Bad.', 9.1),
('Aaron', 'Paul', 'Intenso y emocional en drama.', 8.5),
('Steve', 'Carell', 'Comediante con talento dramático.', 8.3),
('John', 'Krasinski', 'Actor y director en ascenso.', 8.2),
('Jim', 'Carrey', 'Maestro de la comedia física.', 8.4),
('Robin', 'Williams', 'Comediante legendario y actor dramático.', 9.2),
('Heath', 'Ledger', 'Reconocido por su Joker icónico.', 9.3),
('Joseph', 'Gordon-Levitt', 'Actor de cine independiente y comercial.', 8.2),
('Saoirse', 'Ronan', 'Actriz joven con múltiples nominaciones.', 8.8),
('Millie', 'Bobby Brown', 'Joven estrella de Stranger Things.', 8.1),
('Finn', 'Wolfhard', 'Actor y músico canadiense.', 8.0),
('Noah', 'Schnapp', 'Protagonista de Stranger Things.', 7.9),
('David', 'Harbour', 'Popular por su papel como Hopper.', 8.2),
('Winona', 'Ryder', 'Icono de los 90 y figura actual.', 8.3),
('Ewan', 'McGregor', 'Conocido por Star Wars y Moulin Rouge.', 8.5),
('Liam', 'Neeson', 'Actor de acción y drama.', 8.4),
('Colin', 'Firth', 'Ganador del Oscar por The King''s Speech.', 8.6),
('Harrison', 'Ford', 'Icono de Indiana Jones y Han Solo.', 8.7),
('Sylvester', 'Stallone', 'Estrella de acción y Rocky.', 8.0),
('Arnold', 'Schwarzenegger', 'Ícono del cine de acción.', 7.9),
('Jason', 'Statham', 'Especialista en acción física.', 7.8),
('Vin', 'Diesel', 'Famoso por Fast & Furious.', 7.5),
('Bruce', 'Willis', 'Actor de acción de los 90.', 8.1),
('Jack', 'Nicholson', 'Leyenda del cine con múltiples premios.', 9.1),
('Clint', 'Eastwood', 'Actor y director legendario.', 9.0),
('Michael', 'Keaton', 'Conocido por Batman y Birdman.', 8.5),
('George', 'Clooney', 'Actor, director y filántropo.', 8.4),
('Adam', 'Driver', 'Actor versátil y respetado.', 8.6),
('J.K.', 'Simmons', 'Ganador del Oscar por Whiplash.', 8.9),
('Willem', 'Dafoe', 'Actor teatral con gran intensidad.', 8.8),
('Cillian', 'Murphy', 'Conocido por Peaky Blinders y Oppenheimer.', 8.7),
('Pedro', 'Pascal', 'Popular por The Mandalorian.', 8.6),
('Oscar', 'Isaac', 'Actor guatemalteco de renombre.', 8.5);
